# 荒野的召唤
PROCESS-NAME,theHunterCotW_F.exe

DOMAIN,cotw-social.avalanchestudios.com
DOMAIN,cotw-cdn.avalanchestudios.com
DOMAIN,tracking2.avalanchestudios.com

# DOMAIN,api.epicgames.dev
# DOMAIN,turn.rtcp.on.epicgames.com
