#番茄去广告

#番茄短剧
DOMAIN-WILDCARD,-reading-video.fqnovelvod.com

#千阅去广告
DOMAIN,mobads.baidu.com
DOMAIN,open.e.kuaishou.com
DOMAIN-WILDCARD,.gdt.qq.com

#千阅 拦截广告视频加载，上面去广告成功就不需要了
#DOMAIN,pgdt.ugdtimg.com

#不清楚下载的什么，一直加缓存
DOMAIN-WILDCARD,-ad.adkwai.com
DOMAIN-WILDCARD,-ad.adukwai.com
